exports.msg = {
    verificationSuccess: 'Verification sent successfully.',
    otpMessage: 'This is your OTP: 1234. You can now log in.',
    otpVerified: 'Your OTP has been verified successfully.',
    serverError: 'Internal server error. Please try again later.',
    unauthorizedAccess: 'You are not authorized to access this resource.',
    tokenMissing: 'Authorization token is missing.',
    tokenExpired: 'Your session has expired. Please log in again.',
    invalidToken: 'The provided token is invalid.',
    tokenRequired: 'Authorization token is required',
    profileUpdatedSuccessfully: 'Profile updated successfully',
    profileUpdatedFailed: 'Profile not updated',
    dataFoundSuccess: "Data found successfully.",
    dataFoundFailed: "Data not found. Please try again.",
    productAddFailed: 'Failed to add product',
    productAddSuccess: 'Product added successfully',
    productNotFound: "No products found. Please add products to view them here.",
    productFoundSuccess: "Products retrieved successfully.",
    productAlreadyRent: "This product is already rented, so editing and delete is not allowed until it becomes available.",
    productUpdateSuccess: "Product updated successfully.",
    productUpdateFailed: "No product was updated. Please check the product ID or the provided data.",
    productDeleteSuccess: "products deleted successfully.",
    noSubcategoryFound: "No subcategory found for the given category.",
    subCategoryFoundSuccess: "Subcategories retrieved successfully."
};
